import mongoose, { Document, Schema } from 'mongoose';

export interface ITicket extends Document {
  gigId: mongoose.Types.ObjectId;
  fanUserId: mongoose.Types.ObjectId;
  quantity: number;
  totalPrice: number;
  qrCode: string; // data URL generated by qrcode library
  qrToken: string; // unique token encoded in QR (used for door validation)
  status: 'valid' | 'used' | 'cancelled';
  purchasedAt: Date;
}

const TicketSchema = new Schema<ITicket>({
  gigId: { type: Schema.Types.ObjectId, ref: 'Gig', required: true, index: true },
  fanUserId: { type: Schema.Types.ObjectId, ref: 'User', required: true, index: true },
  quantity: { type: Number, required: true, min: 1 },
  totalPrice: { type: Number, required: true, min: 0 },
  qrCode: { type: String, required: true },
  qrToken: { type: String, required: true, unique: true, index: true },
  status: { type: String, enum: ['valid', 'used', 'cancelled'], default: 'valid' },
  purchasedAt: { type: Date, default: Date.now },
});

export const Ticket = mongoose.model<ITicket>('Ticket', TicketSchema);
