import { Event, ArtistApplication, LocalArtist, MockPromoter, Venue, ChatMessage } from './types';

export const getMockEvents = (): Event[] => {
  const currentDate = new Date();
  const currentYear = currentDate.getFullYear();
  const currentMonth = currentDate.getMonth() + 1; // getMonth() returns 0-11, we need 1-12
  
  return [
    {
      id: 1,
      artist: "The Midnight Keys",
      date: `${currentYear}-${String(currentMonth).padStart(2, '0')}-15`,
      time: "8 PM doors",
      genre: "Jazz",
      ticketsSold: 50,
      totalTickets: 75,
      guarantee: 400,
      currentEarnings: 600,
      status: "live",
      applications: 3,
      image: "",
      expectedBands: 3,
      confirmedBands: 3,
    },
    {
      id: 2,
      artist: "Electric Pulse",
      date: `${currentYear}-${String(currentMonth).padStart(2, '0')}-22`,
      time: "9 PM",
      genre: "Electronic",
      ticketsSold: 0,
      totalTickets: 100,
      guarantee: 300,
      currentEarnings: 0,
      status: "posted",
      applications: 7,
      image: "",
      expectedBands: 4,
      confirmedBands: 2,
    },
    {
      id: 3,
      artist: "Acoustic Souls",
      date: `${currentYear}-${String(currentMonth).padStart(2, '0')}-08`,
      time: "7 PM",
      genre: "Folk",
      ticketsSold: 45,
      totalTickets: 60,
      guarantee: 250,
      currentEarnings: 350,
      status: "completed",
      applications: 0,
      image: "",
      expectedBands: 2,
      confirmedBands: 2,
    },
    {
      id: 4,
      artist: "Rock Nation",
      date: `${currentYear}-${String(currentMonth).padStart(2, '0')}-28`,
      time: "8 PM",
      genre: "Rock",
      ticketsSold: 0,
      totalTickets: 80,
      guarantee: 500,
      currentEarnings: 0,
      status: "posted",
      applications: 2,
      image: "",
      expectedBands: 3,
      confirmedBands: 1,
    },
  ];
};

export const getArtistApplications = (): ArtistApplication[] => [
  {
    id: "app1",
    artist: "The Midnight Keys",
    genre: "Jazz",
    rating: 4.8,
    followers: "2.1K",
    bio: "Smooth jazz quartet with over 10 years of experience performing at prestigious locations across the country.",
    image: "/images/BandFallBack.PNG",
  },
  {
    id: "app2",
    artist: "Electric Pulse",
    genre: "Electronic",
    rating: 4.6,
    followers: "5.3K",
    bio: "High-energy electronic duo specializing in house and techno. Known for creating immersive dance experiences.",
    image: "/images/BandFallBack.PNG",
  },
  {
    id: "app3",
    artist: "Acoustic Souls",
    genre: "Folk",
    rating: 4.9,
    followers: "1.8K",
    bio: "Intimate folk trio blending traditional melodies with contemporary storytelling. Perfect for intimate locations.",
    image: "/images/BandFallBack.PNG",
  },
  {
    id: "app4",
    artist: "Rock Nation",
    genre: "Rock",
    rating: 4.4,
    followers: "8.7K",
    bio: "High-octane rock band with a loyal following. Known for electrifying performances and crowd engagement.",
    image: "/images/BandFallBack.PNG",
  },
];

export const getLocalArtists = (): LocalArtist[] => [
  {
    id: "local1",
    artist: "The Blue Notes",
    genre: "Jazz",
    rating: 4.7,
    followers: "3.2K",
    bio: "Local jazz ensemble specializing in smooth jazz and contemporary arrangements. Regular performers at downtown venues.",
    image: "/images/BandFallBack.PNG",
    location: "Downtown",
    priceRange: "$200-400",
    availability: "Available this month",
    instagram: "@thebluenotesjazz",
    spotify: "https://open.spotify.com/artist/thebluenotes",
    appleMusic: "https://music.apple.com/artist/the-blue-notes/123456789",
  },
  {
    id: "local2",
    artist: "Urban Beats",
    genre: "Hip-Hop",
    rating: 4.5,
    followers: "4.8K",
    bio: "Dynamic hip-hop collective bringing fresh beats and powerful lyrics. Known for high-energy performances.",
    image: "/images/BandFallBack.PNG",
    location: "East Side",
    priceRange: "$300-500",
    availability: "Available next week",
    instagram: "@urbanbeatscrew",
    spotify: "https://open.spotify.com/artist/urbanbeats",
    appleMusic: "https://music.apple.com/artist/urban-beats/987654321",
  },
  {
    id: "local3",
    artist: "The Acoustic Trio",
    genre: "Folk",
    rating: 4.9,
    followers: "2.1K",
    bio: "Intimate acoustic performances with beautiful harmonies. Perfect for smaller venues and intimate settings.",
    image: "/images/BandFallBack.PNG",
    location: "West End",
    priceRange: "$150-300",
    availability: "Available this weekend",
    instagram: "@acoustictrio",
    spotify: "https://open.spotify.com/artist/acoustictrio",
    appleMusic: "https://music.apple.com/artist/the-acoustic-trio/456789123",
  },
  {
    id: "local4",
    artist: "Electric Storm",
    genre: "Electronic",
    rating: 4.6,
    followers: "6.7K",
    bio: "Electronic music producers and DJs creating immersive soundscapes. Perfect for late-night events.",
    image: "/images/BandFallBack.PNG",
    location: "Midtown",
    priceRange: "$400-600",
    availability: "Available next month",
    instagram: "@electricstormmusic",
    spotify: "https://open.spotify.com/artist/electricstorm",
    appleMusic: "https://music.apple.com/artist/electric-storm/789123456",
  },
  {
    id: "local5",
    artist: "The Soul Collective",
    genre: "R&B",
    rating: 4.8,
    followers: "5.4K",
    bio: "Soulful R&B group with powerful vocals and smooth instrumentals. Brings the house down every performance.",
    image: "/images/BandFallBack.PNG",
    location: "South Side",
    priceRange: "$350-550",
    availability: "Available in 2 weeks",
    instagram: "@soulcollective",
    spotify: "https://open.spotify.com/artist/soulcollective",
    appleMusic: "https://music.apple.com/artist/the-soul-collective/321654987",
  },
  {
    id: "local6",
    artist: "Indie Dreams",
    genre: "Indie Rock",
    rating: 4.4,
    followers: "3.9K",
    bio: "Indie rock band with catchy melodies and thoughtful lyrics. Great for alternative music lovers.",
    image: "/images/BandFallBack.PNG",
    location: "North District",
    priceRange: "$250-450",
    availability: "Available this month",
    instagram: "@indiedreamsband",
    spotify: "https://open.spotify.com/artist/indiedreams",
    appleMusic: "https://music.apple.com/artist/indie-dreams/654321987",
  },
];

export const getMockPromoters = (): MockPromoter[] => [
  {
    id: "promoter1",
    name: "Jazz Promotions LLC",
    location: "New York, NY",
    type: "Jazz Specialist",
    eventsCount: 8,
    revenue: "$12.4K",
    image: "/images/venu-logo.png",
  },
  {
    id: "promoter2",
    name: "Rock Nation",
    location: "Philadelphia, PA",
    type: "Rock & Metal",
    eventsCount: 12,
    revenue: "$18.7K",
    image: "/images/venu-logo.png",
  },
  {
    id: "promoter3",
    name: "Electronic Vibes",
    location: "Nashville, TN",
    type: "Electronic & EDM",
    eventsCount: 6,
    revenue: "$9.2K",
    image: "/images/venu-logo.png",
  },
];

export const getMyLocations = (): Venue[] => [
  {
    id: "venue1",
    name: "The Blue Note",
    location: "New York, NY",
    capacity: 200,
    type: "Jazz Club",
    image: "/images/venu-logo.png",
    instagram: "@thebluenote",
    eventsCount: 8,
    revenue: "$12.4K",
  },
  {
    id: "venue2",
    name: "Electric Ballroom",
    location: "Philadelphia, PA",
    capacity: 500,
    type: "Concert Hall",
    image: "/images/venu-logo.png",
    instagram: "@electricballroom",
    eventsCount: 12,
    revenue: "$18.7K",
  },
  {
    id: "venue3",
    name: "Acoustic Lounge",
    location: "Nashville, TN",
    capacity: 150,
    type: "Intimate Venue",
    image: "/images/venu-logo.png",
    instagram: "@acousticlounge",
    eventsCount: 6,
    revenue: "$9.2K",
  },
];

export const getChatMessages = (): ChatMessage[] => [
  {
    id: "msg1",
    sender: "The Blue Note",
    message: "Thanks for the great show last night! The crowd loved it.",
    timestamp: "2 hours ago",
    isFromVenue: true,
  },
  {
    id: "msg2",
    sender: "You",
    message: "Thank you! We'd love to book another show next month.",
    timestamp: "1 hour ago",
    isFromVenue: false,
  },
  {
    id: "msg3",
    sender: "Electric Ballroom",
    message: "We have an opening for next Friday. Are you available?",
    timestamp: "30 minutes ago",
    isFromVenue: true,
  },
  {
    id: "msg4",
    sender: "You",
    message: "Yes, we're available! What time would work best?",
    timestamp: "15 minutes ago",
    isFromVenue: false,
  },
];
